---
title: "Term Project"
output: html_document
author: "Liangmi Zhang"
date: "November 24, 2025"
---

```{R importlibrary,,echo = FALSE,eval = TRUE,include = FALSE}
library("haven")
library("survey")
library("jtools")
library("remotes")
library("svrepmisc")
library("dplyr")
library("DT")
library("caret")
library("pROC")
library("car")
```

# Prediction of Coronary Heart Disease with Cholesterol and Trigliceride. 


## Project Inroduction

My lab results showed abnormal cholestrol and triglyceride levels, and the doctor told me that I'm at risk. For this reason,I chose this topic. The initial project plan included doing population parameter analysis too, but it turned out that doing the regression alone took lots of time so the these analysis were given up. 

The main challenge of the project was due to the NHANHE sample design. As a result, NHANHE assigned different weights to different variables/predictors. Understanding the sample design and weights were the most challenging and time-consuming part of this project. 

In a nutshell, this project aims to predict coronary heart disease with high density cholesterol, low density cholesterol and triglyceride.

## Data Introduction.

In 2021- 2023, people partipated in NHANHE's interviews and medical exams.  The organization used multistage sampling to oversample people with certain traits, like certain race, age etc. In addition to other reasons,
NHANHE assigned weights to some variables. For more info about the sample design and weights, please check the source provided below.

The following five datasets were downloaded from the site and merged together by the sequence column.

Demo_L.csv records their demographic info
HDL_L.csv records their high density cholesterol info
TRIGLY_L.csv records the low density cholesterol level and triglyceride levels
TCHOL_L.csv records the total cholesterol level
MCQ_L.csv records the whether they had angina, heart attacks, or cardiavascular diseases. 

L indicates the year is between 2021- 2023. All these files have different rows because only a portion of interview participants decide to take certain lab tests.The Demo_L has the most number of rows because all participants need to provide this info. For information about how the data is preprocessed, please check the two data preprocessing scripts in the project folder.


[Click Here for Data Source](https://wwwn.cdc.gov/nchs/nhanes/search/datapage.aspx?Component=Laboratory&Cycle=2021-2023)



## Logistic Regression

In this section, we try to predict if a person has a coronary heart disease.

### Logistic Regression Without Using Weights

In the beginning, I ignored the various weights in the dataset because I couldn't figure out what they meant and how to use them. However, my models produced AUC around 5. I thought the poor result was because of the missing weights so I decided to use weights to improve the result. However, when I were writing this file, I found out that the low AUC was because of a bug in my original code. After correcting the bug, the ROC looks normal. The corrected result is provided below.


``` {R dataPreparationWithoutWeight, echo = FALSE,include = FALSE}

data = read.csv("cleaned_data.csv")
head(data)

set.seed(123)   # for reproducibility

# First split: train vs rest (2/3 remain)
index1 <- createDataPartition(data$coronary, p = 1/3, list = FALSE)
train <- data[index1, ]
rest  <- data[-index1, ]

# Second split: validation vs test (each 1/3 of full data)
index2 <- createDataPartition(rest$coronary, p = 1/2, list = FALSE)
validation <- rest[index2, ]
test <- rest[-index2, ]

```

Training with 3 predictors

``` {R fittingModelWithoutWeightMultiplePredictors, echo = TRUE,include = TRUE}

# -----model with multiple predictors-----------.
# 1. Fit on training set
model <- glm(
  coronary ~ high_density_level + low_density_level + triglyceride_level,
  family = binomial,
  data = train
)

# 2. Predict on *validation* set
validation$prob <- predict(
  model,
  newdata = validation,
  type = "response"
)

# 3. ROC on validation set

g <- roc(response = validation$coronary,
         predictor = validation$prob)

g
plot(g)
```

Training with one predictor.

``` {R fittingModelWithoutWeightOnePredictor, echo = TRUE,include = TRUE}
# --------- 1. Fit model on TRAIN only --------------

model <- glm(
  coronary ~ low_density_level,
  family = binomial,
  data = train
)

# --------- 2. Predict on VALIDATION only -----------

validation$prob <- predict(
  model,
  newdata = validation,
  type = "response"
)

# --------- 3. Compute ROC on VALIDATION -----------

library(pROC)

g <- roc(
  response  = validation$coronary,
  predictor = validation$prob
)

g
plot(g)
```


### Logistic Regression With Weights

Because of low AUC values due to the bug and my belief that it was caused by ignoring weights, I decided to integrate weights in the regression. In order to learn how to use them, I studied NAHNAES's sample design, a concept that I haven't studied before and struggled to understand. Another challenge was to choose a weight since there were two weights in the dataset. It took me a while to understand the criteria - choose the weight for the smallest subsample if multiple subsamples are used in the analysis. In my case, I needed to decide which subsample was smaller because I had two: the phlebotomy subsample(people who gave blood specimen) and the fasting subsample (people who were asked to fast). It took me several hours just to decide on this. Finally, I found out that fasting subsample was smaller because people in the sample fasted first and then gave blood specimen.


#### Logistic Regression With Using Weight_2(Fasting Subsample Weight)

In the beginning,the models couldn't converge, no matter the number of predictors that I used. This turned out to be another bug that I didn't notice I thought the failure was due to lack of datapoints in the subsample because the fasting subsample was the smallest subsample. However, somehow, the models could converge after some changes that I made, but I lost track of what change I made. 

Regression with weight 2 was presented below. In order to use weight, __svydesign()__ must be used to construct the design object and this object need to be used in the regression. 

```{R loadData2,,echo = FALSE,eval = TRUE,include = FALSE}
result = read.csv("cleaned_data_with_weights.csv")
```


```{R weight2Prepare,,echo = FALSE,eval = TRUE,include = FALSE }
result = subset(result, !is.na(result$weight_2))
# First split: train vs rest (2/3 remain)
index1 <- createDataPartition(result$SEQN, p = 1/3, list = FALSE)
train <- result[index1, ]
rest  <- result[-index1, ]

# Second split: validation vs test (each 1/3 of full data)
index2 <- createDataPartition(rest$SEQN, p = 1/2, list = FALSE)
validation <- rest[index2, ]
test <- rest[-index2, ]

# make the design object for train, validation,test
design_train <- svydesign(
  ids = ~SDMVPSU,
  strata = ~SDMVSTRA,
  weights = ~weight_2, # using the smaller subsample weight - fasting weight.
  nest = TRUE,
  data = train
)


design_validation <- svydesign(
  ids = ~SDMVPSU,
  strata = ~SDMVSTRA,
  weights = ~weight_2, # using the smaller subsample weight - fasting weight.
  nest = TRUE,
  data = validation
)

design_test <- svydesign(
  ids = ~SDMVPSU,
  strata = ~SDMVSTRA,
  weights = ~weight_2, # using the smaller subsample weight - fasting weight.
  nest = TRUE,
  data = test
)

# filter out columns with missing values. 
# We should subset on the design object directly instead of the the dataframe.

design_train_sub <- subset(design_train,
                           !is.na(coronary) &
                             !is.na(high_density_level) &
                             !is.na(low_density_level)&
                             !is.na(triglyceride_level)
                           )
nrow(design_train_sub)

design_validation_sub <- subset(design_validation,
                                !is.na(coronary) &
                                  !is.na(high_density_level) &
                                  !is.na(low_density_level)&
                                  !is.na(triglyceride_level)
                                
                                )
                                  
nrow(design_validation_sub)

design_test_sub <- subset(design_test,
                          !is.na(coronary) &
                            !is.na(high_density_level) &
                            !is.na(low_density_level)&
                            !is.na(triglyceride_level))
nrow(design_test_sub)
result = subset(result, !is.na(result$weight_2))


```

Fitting a model 3 predictors

```{R weight2with3predictors,echo = TRUE,include = TRUE}
# --------- model with 3 predictors -----------------------
# train model on the train set
model1 <- svyglm(
  coronary ~ high_density_level +low_density_level +triglyceride_level  ,
  design = design_train_sub,
  family = quasibinomial()
)

# predict on the validation set.

val_df <- design_validation_sub$variables
val_df$predicted <- predict(model1, newdata = val_df, type = "response")

roc_val_three <- roc(
  response = val_df$coronary,
  predictor = val_df$predicted,
  weights = val_df$weight_2
)

roc_val_three

plot(roc_val_three)

```


Fitting another model with low_density_cholesterol.

```{R weight2with1predictor,echo = TRUE,include = TRUE}
# --------- model one predictor : low density level -----------------------

# train model on the train set
model5 <- svyglm(
  coronary ~ low_density_level ,
  design = design_train_sub,
  family = quasibinomial()
)

summary(model5)

# predict on the validation set.

val_df <- design_validation_sub$variables
val_df$predicted <- predict(model5, newdata = val_df, type = "response")

roc_val_LDL <- roc(
  response = val_df$coronary,
  predictor = val_df$predicted,
  weights = val_df$weight_2
)

roc_val_LDL
plot(roc_val_LDL)
```


#### Logistic Regression With Using Weight_1(Phlebotomy Subsample Weight)

Since my initial attempts to use weight_2(fast subsample weight), the Phlebotomy weight was used because it was the weight for the second smallest subsample and also our only choice left. 


```{R loadData3,,echo = FALSE,eval = TRUE,include = FALSE}
result = read.csv("cleaned_data_with_weights.csv")
```

```{R weight1Preparation, echo = FALSE,include = FALSE}

result = subset(result, !is.na(result$weight_1))

# First split: train vs rest (2/3 remain)
index1 <- createDataPartition(result$SEQN, p = 1/3, list = FALSE)
train <- result[index1, ]
rest  <- result[-index1, ]

# Second split: validation vs test (each 1/3 of full data)
index2 <- createDataPartition(rest$SEQN, p = 1/2, list = FALSE)
validation <- rest[index2, ]
test <- rest[-index2, ]

# make the design object for train, validation,test
design_train <- svydesign(
  ids = ~SDMVPSU,
  strata = ~SDMVSTRA,
  weights = ~weight_1, # using the smaller subsample weight - fasting weight.
  nest = TRUE,
  data = train
)


design_validation <- svydesign(
  ids = ~SDMVPSU,
  strata = ~SDMVSTRA,
  weights = ~weight_1, # using the smaller subsample weight - fasting weight.
  nest = TRUE,
  data = validation
)

design_test <- svydesign(
  ids = ~SDMVPSU,
  strata = ~SDMVSTRA,
  weights = ~weight_1, # using the smaller subsample weight - fasting weight.
  nest = TRUE,
  data = test
)

# filter out columns with missing values. 
# We should subset on the design object directly instead of the the dataframe.

design_train_sub <- subset(design_train,
                     !is.na(coronary) &
                       !is.na(high_density_level) &
                       !is.na(low_density_level))
nrow(design_train_sub)

design_validation_sub <- subset(design_validation,
                           !is.na(coronary) &
                             !is.na(high_density_level) &
                             !is.na(low_density_level))
nrow(design_validation_sub)

design_test_sub <- subset(design_test,
                           !is.na(coronary) &
                             !is.na(high_density_level) &
                             !is.na(low_density_level))
nrow(design_test_sub)

```

##### Logistic Regression With Using Weight_1 and Two Predictors

Fitting a model using high_density_level and low_density_level. The triglyceride_level cannot be used here.

```{R regressionWithWeight_1With2Predictors, echo = TRUE,include = TRUE}
# --------- model with two predictors -----------------------
# train model on the train set
model <- svyglm(
  coronary ~ high_density_level +low_density_level ,
  design = design_train_sub,
  family = quasibinomial()
)

summary(model)

# predict on the validation set.

val_df <- design_validation_sub$variables
val_df$predicted <- predict(model, newdata = val_df, type = "response")

roc_val_both <- roc(
  response = val_df$coronary,
  predictor = val_df$predicted,
  weights = val_df$weight_1
)

roc_val_both

plot(roc_val_both)

```


##### Logistic Regression With Using Weight_1 and One Predictor

We fit another model with low_density_level.

```{R regressionWithWeight_1With1LDL, echo = TRUE,include = TRUE}
# train model on the train set
model <- svyglm(
  coronary ~ low_density_level ,
  design = design_train_sub,
  family = quasibinomial()
)

summary(model)

# predict on the validation set.

val_df <- design_validation_sub$variables
val_df$predicted <- predict(model, newdata = val_df, type = "response")

roc_val_LDL <- roc(
  response = val_df$coronary,
  predictor = val_df$predicted,
  weights = val_df$weight_1
)

roc_val_LDL

plot(roc_val_LDL)

```


## Conclusion

Even though NHANHE used multistage sampling to oversample certain subgroups the population and they emphasize that weights should be used regression, the impact of not using the weights or using a less ideal weight doesn't have much impact on the prediction results. For a logistic regression with one variable low_density_level, there is not much differences in the AUC value of the fitted models, whether the model used weights or used different weight not. 



For the last model,a SLR with weight_1, we choose a threshhold that yields the highest accuracy.

``` {R name, echo = TRUE,include = TRUE}

# 1.choose the best threshold for this model and calculate the accuracy. 

roc_obj <- roc(response = val_df$coronary, predictor = val_df$predicted)
best <- coords(roc_obj, "best", best.method="closest.topleft")
best

best_threshold <- as.numeric(best$threshold)

# 2. predicted classes using optimal threshold
val_df$predicted_labels <- ifelse(val_df$predicted >= best_threshold[], 1, 0)

# 3. accuracy
accuracy <- mean(val_df$predicted_labels == val_df$coronary)
accuracy
```



